# Analysis 

*Die Ziele und Materialien zu diesem Kapitel werden demnächst ergänzt.*



## Analysis in der Sek. II


Der Analysisunterricht in der Schule unterscheidet sich wesentlich von dem in der Hochschule, womit aus fachlicher wie fachdidaktischer Sicht einige Herausforderungen einhergehen. Neben der grundsätzlichen nicht streng deduktiven Herangehensweise werden i. d. R. zentrale Begriffe der Analysis im Schulunterricht kaum oder nur propädeutisch-anschaulich behandelt. Die betrifft zunächst einmal den **Folgen-, Grenzwert- und Stetigkeitsbegriff** [ @Tietze:2000a {252 ff.}; @Danckwerts2010 {17 ff.}; @Greefrath2016 {23 ff.}]. Der Ableitungsbegriff bedarf bspw. des Grenzwertes des Differenzenquotienten. Ein solcher Grenzwert einer Funktion $f$ an einer Stelle $a$ existiert, wenn für alle Folgen $(x_n)_{n\in\mathbb{N}}$ mit $x_n\rightarrow a$ auch die Folge der Funktionswerte konvergiert, also $f(x_n)\rightarrow f(a)$. Für den Konvergenzbegriff einer Folge ist nun zum anderen die **Vollständigkeit der reellen Zahlen** von enormer Bedeutung, was ebenfalls in der Schule nicht in einer derartigen Strenge behandelt wird [siehe z. B. @Danckwerts2010 {27 ff.}]. Mathematisch relevant ist für die Konvergenz einer Folge $(x_n)_{n\in\mathbb{N}}$ gegen $a$ eben nicht nur, dass die Folgenglieder dem $a$ beliebig nahe kommen, sondern dass $a$ im betrachteten Zahlbereich tatsächlich existiert. Ein klassisches Beispiel hierfür ist das Heron-Verfahren zum Wurzelbestimmen (vgl. Abschnitt \@ref(heron-verfahren)). So liefert die rekursive Folge$x_{n+1} = \frac{1}{2}\left(x_n + \frac{5}{x_n}\right)$ mit bspw. $x_0 = 1$ ausschließlich Folgenglieder aus $\mathbb{Q}$, die sich auch beliebig nahe kommen (eine sogenannte *Cauchy-Folge*), der Grenzwert selbst ist aber $\sqrt{5}$, was nicht in $\mathbb{Q}$, sondern nur in $\mathbb{R}$ liegt.

Ohne derartige zentrale (im fachmathematischen Sinne sauber ausgeprägte) Begriffe Analysisunterricht zu betreiben, bedarf also einer starken Orientierung an den hinter den Begriffen liegenden Grundvorstellungen, damit dennoch ein inhaltlich-anschauliches Verständnis aufgebaut werden kann und der Unterricht nicht zu einem kalkülhaften Vorgehen verkommt. Spezifische Anregungen für einzelne Lerngegenstände bieten die bereits zitierten Quellen.

## Grenzwertbegriff 

*Die Inhalte zu diesem Abschnitt werden demnächst ergänzt.*

## Ableitungsbegriff

Für den Ableitungsbegriff (einer Funktion an einer Stelle) haben sich sowohl historisch als auch in der fachdidaktischen Literatur zwei wesentliche Vorstellungen herausgebildet [@Greefrath2016 {147 ff.}; @Danckwerts2010 {45 ff.}]^[@Greefrath2016 [{147 ff.}] trennen die lokale Änderungsrate noch von der Vorstellung des Anstiegs der Tangente und beschreiben als vierte Grundvorstellung die Ableitung als Verstärkungsfaktor kleiner Änderungen.]:

* Ableitung als **lokale Änderungsrate**: Die Ableitung einer Funktion an einer Stelle beschreibt, wie stark sich die Funktionswerte in der Umgebung dieser Stelle verändern. Wird sich dieser Änderungsrate graphisch genähert, erfolgt dies i. d. R. durch den Übergang des Anstiegs einer Sekante zu dem einer Tangente^[Zur Diskussion der Vorstellung, was eine Tangente ist, siehe auch @Greefrath2016 [149]], womit die Ableitung über den **Grenzwert des Differenzenquotienten** $\lim\limits_{h\rightarrow 0}\cfrac{f(x_0+h)-f(x_0)}{h}$ quantifiziert werden kann und dem **Anstieg der Tangente** entspricht.

  Diese Sichtweise ermöglicht, den Ableitungbegriff konstruktiv über den Sekanten-Tangenten-Übergang einzuführen und unmittelbar numerisch zu beschreiben. Auch bedienen sich vielfältige Anwendungen (z. B. Momentan- vs. Durchschnittsgeschwindigkeit) dieser Vorstellung.

* Ableitung als **lokale lineare Approximation**: Diese Vorstellung betont noch stärker die Differenzierbarkeit als Eigenschaft einer Funktion, nämlich die Möglichkeit, sie lokal durch eine lineare Funktion annähern zu können. Eine typische Repräsentation ist das Heranzoomen an den Funktionsgraphen, sodass dabei die lokale Linearität besonders deutlich wird. Mathematisch greifbar wird diese Vorstellung darüber, dass sich die Funktion über $f(x) = f(x_0) + m\cdot x+ r(h)$ beschreiben lässt, wobei der *Fehler* $r(h)$ so schnell gegen $0$ geht, dass sogar $\lim\limits_{h\rightarrow 0}\cfrac{r(h)}{h}=0$ gilt. $m$ selbst ist dann die Ableitung und der Anstieg der *besten linearen Näherung* -- was natürlich wieder die Tangente an entsprechender Stelle ist.


  Dieses Vorgehen besticht v. a. durch seine mathematische Verallgemeinerbarkeit für die höherdimensionale Analysis. Auch entspricht es dem Bedürfnis, Prozesse linear zu approximieren (vgl. Abschnitt \@ref(beispiel-linearitaet)).



## Computer-Algebra-Systeme

*Die Inhalte zu diesem Abschnitt werden demnächst ergänzt.*

